# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import market_data_pb2 as market__data__pb2


class MarketDataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListenMarketData = channel.unary_stream(
                '/MarketData/ListenMarketData',
                request_serializer=market__data__pb2.MarketDataRequest.SerializeToString,
                response_deserializer=market__data__pb2.MarketDataResponse.FromString,
                )


class MarketDataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListenMarketData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListenMarketData': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenMarketData,
                    request_deserializer=market__data__pb2.MarketDataRequest.FromString,
                    response_serializer=market__data__pb2.MarketDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MarketData', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MarketData(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListenMarketData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/MarketData/ListenMarketData',
            market__data__pb2.MarketDataRequest.SerializeToString,
            market__data__pb2.MarketDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
