# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11market_data.proto\"$\n\x11MarketDataRequest\x12\x0f\n\x07trigger\x18\x01 \x01(\t\">\n\x12MarketDataResponse\x12\r\n\x05price\x18\x01 \x01(\x02\x12\x0b\n\x03vol\x18\x02 \x01(\x02\x12\x0c\n\x04side\x18\x03 \x01(\t2M\n\nMarketData\x12?\n\x10ListenMarketData\x12\x12.MarketDataRequest\x1a\x13.MarketDataResponse\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MARKETDATAREQUEST._serialized_start=21
  _MARKETDATAREQUEST._serialized_end=57
  _MARKETDATARESPONSE._serialized_start=59
  _MARKETDATARESPONSE._serialized_end=121
  _MARKETDATA._serialized_start=123
  _MARKETDATA._serialized_end=200
# @@protoc_insertion_point(module_scope)
